FROM openjdk:17
COPY bottle-bottlesv-dev-0.0.1-SNAPSHOT.jar /usr/src/myapp/bottle-bottlesv-dev-0.0.1-SNAPSHOT.jar
WORKDIR /usr/src/myapp
ENTRYPOINT ["java", "-Dspring.profiles.active=dev", "-jar", "/usr/src/myapp/bottle-bottlesv-dev-0.0.1-SNAPSHOT.jar"]
EXPOSE 8080