# 1단계: React build
FROM node:18 AS builder
WORKDIR /app

# package.json 복사 후 설치
COPY package*.json ./
RUN npm ci

# 소스 전체 복사
COPY . ./
RUN npm run build

# 2단계: Nginx
FROM nginx:1.25-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
