# 1단계: React build
FROM node:18 AS builder
WORKDIR /app

# 소스 전체 복사
COPY web/ ./web
WORKDIR /app/web

RUN npm install --legacy-peer-deps
RUN npm run build

# 2단계: Nginx
FROM nginx:1.25-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/web/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]