pipeline {
    agent any

    environment {
        DOCKERHUB_USERNAME = 'agida0413'
        SOURCE_REPO = 'https://github.com/Bottle-Story/bottle-story-frontend.git'
        DEVOPS_REPO = 'https://github.com/Bottle-Story/bottle-story-devops.git'
        FRONTEND_DIR = 'frontend'
        WEB_SRC_DIR = 'web-src'
    }

    stages {
        stage('프론트엔드 소스 체크아웃') {
            steps {
                dir("${WEB_SRC_DIR}") {
                    git branch: 'develop', url: "${SOURCE_REPO}"
                }
            }
        }

        stage('DevOps 레포 체크아웃') {
            steps {
                dir("${FRONTEND_DIR}") {
                    git branch: 'main', url: "${DEVOPS_REPO}"
                }
            }
        }

        stage('소스 복사') {
            steps {
                sh """
                    # 기존 frontend 소스 제거 후 web-src 복사
                    rsync -av --delete ${WEB_SRC_DIR}/ ${FRONTEND_DIR}/
                """
            }
        }

        stage('Docker 이미지 빌드 및 Push') {
            steps {
                sh """
                    echo "Docker 로그인"
                    echo '${DOCKERHUB_PASSWORD}' | docker login -u '${DOCKERHUB_USERNAME}' --password-stdin

                    echo "Docker 이미지 빌드"
                    docker build -t ${DOCKERHUB_USERNAME}/frontend-bottle:latest -f ${FRONTEND_DIR}/Dockerfile-dev ${FRONTEND_DIR}

                    echo "Docker 이미지 푸시"
                    docker push ${DOCKERHUB_USERNAME}/frontend-bottle:latest
                """
            }
        }

        stage('쿠버네티스 배포') {
            steps {
                withCredentials([file(credentialsId: 'k8s_master_config', variable: 'KUBECONFIG')]) {
                    sh """
                        helm upgrade --install frontend-bottle ${FRONTEND_DIR}/helm \
                        --values ${FRONTEND_DIR}/helm/values-dev.yaml \
                        --namespace frontend-bottle
                    """
                }
            }
        }
    }
}
