pipeline {
    agent any

    environment {
        DOCKERHUB_USERNAME = 'agida0413'
        SOURCE_REPO = 'https://github.com/Bottle-Story/bottle-story-frontend.git'
        DEVOPS_REPO = 'https://github.com/Bottle-Story/bottle-story-devops.git'
        FRONTEND_DIR = 'frontend'
    }

    stages {
        stage('소스 레포 체크아웃') {
            steps {
                // frontend 레포지토리에서 develop 브랜치 체크아웃
                dir("${FRONTEND_DIR}") {
                    git branch: 'develop', url: "${SOURCE_REPO}"
                }
            }
        }

        stage('데브옵스 레포 체크아웃') {
            steps {
                // devops 레포지토리에서 main 브랜치 체크아웃
                dir("${FRONTEND_DIR}") {
                    git branch: 'main', url: "${DEVOPS_REPO}"
                }
            }
        }

        stage('Docker 이미지 빌드 및 Push') {
            steps {
                dir("${FRONTEND_DIR}") {
                    withCredentials([usernamePassword(credentialsId: 'docker_password', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                        sh 'echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin'
                    }

                    // Dockerfile-dev를 기준으로 빌드 컨텍스트는 frontend/
                    sh "docker build -t ${DOCKERHUB_USERNAME}/frontend-bottle:latest -f Dockerfile-dev ."
                    sh "docker push ${DOCKERHUB_USERNAME}/frontend-bottle:latest"
                }
            }
        }

        stage('쿠버네티스 배포') {
            steps {
                withCredentials([file(credentialsId: 'k8s_master_config', variable: 'KUBECONFIG')]) {
                    sh """
                        helm upgrade --install frontend-bottle ${FRONTEND_DIR}/helm \
                        --values ${FRONTEND_DIR}/helm/values-dev.yaml \
                        --namespace frontend-bottle
                    """
                }
            }
        }
    }
}
