pipeline {
    agent any

    environment {
        DOCKERHUB_USERNAME = 'agida0413'
        SOURCE_REPO = 'https://github.com/Bottle-Story/bottle-story-frontend.git'
        DEVOPS_REPO  = 'https://github.com/Bottle-Story/bottle-story-devops.git'
        DEVOPS_DIR   = 'frontend'
    }

    stages {
        stage('소스 레포 체크아웃') {
            steps {
                dir('web-src') {
                    git branch: 'develop', url: "${SOURCE_REPO}"
                }
            }
        }

        stage('데브옵스 레포 체크아웃') {
            steps {
                dir("${DEVOPS_DIR}") {
                    git branch: 'main', url: "${DEVOPS_REPO}"
                }
            }
        }

        stage('소스 파일 복사') {
            steps {
                sh """
                    # 데브옵스 폴더 안으로 web-src 복사
                    rm -rf ${DEVOPS_DIR}/web
                    cp -r web-src/web ${DEVOPS_DIR}/
                """
            }
        }

        stage('Docker 이미지 빌드 및 Push') {
            steps {
                dir("${DEVOPS_DIR}") {
                    withCredentials([usernamePassword(credentialsId: 'docker_password', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                        sh '''
                            echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
                        '''
                    }

                    sh "docker build --no-cache -t ${DOCKERHUB_USERNAME}/frontend-bottle:latest -f Dockerfile-dev ."
                    sh "docker push ${DOCKERHUB_USERNAME}/frontend-bottle:latest"
                }
            }
        }

        stage('쿠버네티스 배포') {
            steps {
                withCredentials([file(credentialsId: 'k8s_master_config', variable: 'KUBECONFIG')]) {
                    sh """
                        helm upgrade --install frontend-bottle ${DEVOPS_DIR}/helm \
                        --values ${DEVOPS_DIR}/helm/values-dev.yaml \
                        --namespace backend-bottle
                    """
                }
            }
        }
    }
}
